AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
    - gemfiles/*
    - Appraisals
    - lib/generators/create_slugs.erb.rb

inherit_from: .rubocop_todo.yml

Layout/AlignParameters:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Lint/HandleExceptions:
  Exclude:
    - 'test/test_helper.rb'

Style/Documentation:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  EnforcedStyle: double_quotes

