AllCops:
  TargetRubyVersion: 3.0
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - gemfiles/*
    - Appraisals
    - lib/generators/create_slugs.erb.rb

inherit_from: .rubocop_todo.yml

Layout/ParameterAlignment:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Lint/SuppressedException:
  Exclude:
    - "test/test_helper.rb"

Metrics/BlockLength:
  Exclude:
    - "bench.rb"

Style/Documentation:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  EnforcedStyle: double_quotes
