language: ruby
cache: bundler
sudo: false
rvm:
  - 2.5.3
  - 2.4.5
  - 2.3.8
gemfile:
  - gemfiles/ar51.gemfile
  - gemfiles/ar52.gemfile
before_install: "gem update --system" # https://github.com/travis-ci/travis-ci/issues/8974
